server:
  port: 80

person:
  lastName: zhangsan
  age: 89
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: v2}
  lists:
    -lisi
    -zhaoliu
  dog:
    name: wang
    age: 3
spring:
  redis:
    host: 172.16.17.200