server:
  port: 8010

#person:
#    age: 18
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: v2}
#    lists:
#        - lisi
#        - zhaoliu
#    dog:
#      name: WangCai
#      age: 2
#    last_name: zhangsan

